baseURL = 'https://hugo-libertydengyong.vercel.app//'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"
defaultContentLanguage = "zh" 
[params]
  defaultTheme = "light"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableScrollToTop = false

  [params.homeInfoParams]
    Title = "欢迎来到我的博客！"
    Content = "这里记录了我的想法、学习笔记和生活点滴。"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "archives/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "tags/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "search/"
    weight = 30

[Languages]
  [Languages.en]
    contentDir = "content/english"
    languageName = "English"
    weight = 1

  [Languages.zh]
    contentDir = "content/chinese"
    languageName = "中文"
    weight = 2

[markup.highlight]
  noClasses = false
